### ISSUE TITLE
Iframe not working for internet explorer in Mendix 6.10.10

### ISSUE THREAD

**Issue by ADoppenberg** [mendix/IFrame#4]
We have an application running is Mendix version 6.10.10. This application is used in an different website through an Iframe solution. The problem is that it doesn't work with internet explorer. All other browsers are working,but when we access it through internet explorer we get a grey screen. 

When I inspect the element it states that for mxui.js the permission is denied. I added a screenshot of that statement.
![internet explorer mxui](https://user-images.githubusercontent.com/37397846/37451371-98c9e790-2831-11e8-8495-d1207921ab20.PNG)

The Mendix support stated it might be solved in Mendix 7, but unfortunately it is not possible to do this at this point and therefore we are looking for a different solution.

**Comment by JelteMX** [comment]
This is confusing. The issue states that you are running a Mendix Application and you want this to be shown in an iframe on a different website? I believe that's the case, which makes this issue on Github obsolete, as it has nothing to do with the IFrame widget.

There is a cloud setting that will prevent your Mendix application from being shown in an iframe. Here's a screenshot:

![image 1](https://user-images.githubusercontent.com/14937393/37660722-58a8acd4-2c53-11e8-90b6-2441b1736529.png)

I am referring you back to Mendix Support on this. Furthermore, R&D (WebUI) is responsible for the mxui-client, so they are the ones that should pick it up.

As this issue has nothing to do with the IFrame Widget, I am closing the issue.
