### ISSUE TITLE
iframe widget not working in 9.05 release

### ISSUE THREAD

**Issue by rpassmore1** [mendix/IFrame#5]
Hi ,

As per this forum posts, the iframe widget is currently now working with Mendix release 9.0.5. 

https://forum.mendixcloud.com/link/questions/106233

We are also having the same issue after upgrading from 9.0.2 to 9.0.5 – the iFrame widget does not render and we get the same error in the app as the above post.

Any information to help on this issue as we really need iFrame functionality to render core functionality in our apps…

Kind regards
Rob

**Comment by JelteMX** [comment]
Fixed in [3.1.2](https://github.com/mendixlabs/IFrame/releases/tag/v3.1.2)
