### ISSUE TITLE
Move to platform support

### ISSUE THREAD

**Issue by woutervanmaasakker** [mendix/IFrame#6]
Hi guys,

I wonder, is it possible to move this widget to platform support by Mendix? Or will it remain community support?

Wouter.

**Comment by JelteMX** [comment]
Don't count on it. The reason for that is two-fold:

- It is using Dojo. As we've moved on to React, the platform will eventually stop using Dojo and this widget will not be working anymore
- It is a simple iframe, nothing special there. This could also be done with any other widget like FormatString (or have a look at my newer [IFrame Component](https://marketplace.mendix.com/link/component/117308)
